services:
  waveview-web:
    build: .
    ports:
      - "5333:5333"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://veps-api.cendana15.com
      - VITE_WS_URL=wss://veps-api.cendana15.com
      - VITE_BUILD_VENDOR=cendana15
